### ISSUE TITLE
Connect to wallet by private key

### ISSUE THREAD

**Issue by siliconstack** [AlphaX-IBS/ax-raffle#14]
1. when click on button "connect" or "buy now", open pop up below to select metamask or private key:
<img width="522" alt="image" src="https://user-images.githubusercontent.com/37410895/46538490-6655e400-c8de-11e8-8eb1-82d72e22236e.png">

code in scene/PlayOnline/index.js: 
```javascript
<Modal
  isOpen={modal}
  toggle={this.toggleModal}
  className={this.props.className}
>
  <ModalHeader className="text-center" toggle={this.toggleModal}>
    Connect to your wallet through
  </ModalHeader>
  <ModalBody className="text-center">
    Connecting to Metamask is required to use this function.
    <p />
    <Row className="justify-content-center">
      <Col xs={4} md={3}>
        <Button color="" onClick={this.connectAccount}>
          <img src="/img/metamask.png" style={{height:48}}></img>
          <p>Metamask</p>
        </Button>
      </Col>
      <Col xs={4} md={3}>
        <Button color="" onClick={this.connectAccount}>
          <img src="/img/key.png" style={{height:48}}></img>
          <p>Private Key</p>
        </Button>
      </Col>
    </Row>
    <p />
  </ModalBody>
  <ModalFooter />
</Modal>
```

2. code web3 using private key:
```javascript
const provider = new HttpHeaderProvider(
        "https://ropsten.infura.io",
        headers
      );
      web3 = new Web3(provider);
      const privateKey =
        "4BFCF4A3A56FFB78D7D06A7132F245C2843A365810E3DF225A4EFE3B9322527E313";
      const account = web3.eth.accounts.privateKeyToAccount("0x" + privateKey);
      web3.eth.accounts.wallet.add(account);
      web3.eth.defaultAccount = account.address;
      console.log("Injected private key detected.");
      console.log(account);
      resolve(web3);
```

3. after successfully input private key or connect to metamask, return address and display avatar as screenshot:
<img width="312" alt="image" src="https://user-images.githubusercontent.com/37410895/46538959-81752380-c8df-11e8-953a-614753d28bea.png">

4. after logged in, user can buy ticket.

(logo below)

![key](https://user-images.githubusercontent.com/37410895/46539941-1da02a00-c8e2-11e8-8904-6a63d47c0f3f.png)
![metamask](https://user-images.githubusercontent.com/37410895/46539942-1e38c080-c8e2-11e8-8ea1-e1dfb848209e.png)

**Comment by jaycob-gex** [comment]
pull request https://github.com/AlphaX-IBS/ax-raffle/pull/15

**Comment by dennisd74** [comment]
@TobyIO confirmed closing it
